all:
  children:
    holosite:     
      hosts:            
        haachama:                 
          ansible_host: 10.10.0.72
      vars:
        ansible_user: fishsauce
        ansible_port: 22
